"""guideline chunks linkouts

Revision ID: fd5584f863b5
Revises: e829c052a910
Create Date: 2026-09-22 02:05:15.517041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd5584f863b5'
down_revision: Union[str, Sequence[str], None] = 'e829c052a910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guideline_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('guideline_version', sa.String(length=64), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('crawl_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('precedence_key', sa.String(length=256), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('search_tsv', postgresql.TSVECTOR().with_variant(sa.Text(), 'sqlite'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guideline_chunks_content_hash'), 'guideline_chunks', ['content_hash'], unique=False)
    op.create_index(op.f('ix_guideline_chunks_precedence_key'), 'guideline_chunks', ['precedence_key'], unique=False)
    op.create_index(op.f('ix_guideline_chunks_source'), 'guideline_chunks', ['source'], unique=False)
    op.create_index(op.f('ix_guideline_chunks_source_url'), 'guideline_chunks', ['source_url'], unique=False)
    op.create_table('linkouts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic', sa.String(length=256), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('lastmod', sa.String(length=32), nullable=True),
    sa.Column('crawl_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic', 'url')
    )
    op.create_index(op.f('ix_linkouts_topic'), 'linkouts', ['topic'], unique=False)
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            "CREATE TRIGGER guideline_chunks_tsv_update BEFORE INSERT OR UPDATE "
            "OF title, text ON guideline_chunks FOR EACH ROW EXECUTE FUNCTION "
            "tsvector_update_trigger(search_tsv, 'pg_catalog.german', title, text)"
        )
        op.execute(
            "CREATE INDEX ix_guideline_chunks_search_tsv ON guideline_chunks "
            "USING GIN (search_tsv)"
        )


def downgrade() -> None:
    """Downgrade schema."""
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP TRIGGER IF EXISTS guideline_chunks_tsv_update ON guideline_chunks")
        op.execute("DROP INDEX IF EXISTS ix_guideline_chunks_search_tsv")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_linkouts_topic'), table_name='linkouts')
    op.drop_table('linkouts')
    op.drop_index(op.f('ix_guideline_chunks_source_url'), table_name='guideline_chunks')
    op.drop_index(op.f('ix_guideline_chunks_source'), table_name='guideline_chunks')
    op.drop_index(op.f('ix_guideline_chunks_precedence_key'), table_name='guideline_chunks')
    op.drop_index(op.f('ix_guideline_chunks_content_hash'), table_name='guideline_chunks')
    op.drop_table('guideline_chunks')
    # ### end Alembic commands ###
